### ISSUE TITLE
Adding in the rule head

### ISSUE THREAD

**Issue by remysucre** [Hacker0912/RecStep#2]
I have a program that computes the lengths of all paths in a weighted graph: 
```
EDB_DECL:
arc(x int, y int, z int)

IDB_DECL:
path(x int, y int, w int)

RULE_DECL:
path(x, y, w) :- arc(x, y, w).
path(x, y, d1+d2) :- path(x, z, d1), arc(z, y, d2).
```
But RecStep does not seem to compute d1+d2 correctly. For example, on the following input all paths are assigned the length of 1: 
```
1,2,1
2,3,1
3,4,1
4,5,1
```

**Comment by Hacker0912** [comment]
Hi Remy,

Thanks for your interests in RecStep! Being implemented as a research prototype, we actually just focused on the functionality supports for the set of queries we were interested in at the time (although the optimizations are general) when we started the project. Thus "math expression" included in the head atom of the Datalog rule was not actually supported before since no such rule was involved in the Datalog programs we were interested in. 

But since adding this functionality seems to be an easy task, I just added it and pushed the new code. Now when you run the program on the toy example provided by you, you should be able to get the following correct output:

![output](https://user-images.githubusercontent.com/8917837/106666312-0c788e00-656d-11eb-8ca6-49c4fcdd5c5a.png)

We would like to make RecStep more useful by adding more functional support and fixing potential bugs found. So feel free to reach if you encounter any other issues while using it. 

Thanks,
Zhiwei

**Comment by remysucre** [comment]
Excellent, thank you!
