### ISSUE TITLE
Issue with SUM aggregate

### ISSUE THREAD

**Issue by remysucre** [Hacker0912/RecStep#4]
I ran into some type errors when trying to use the `SUM` aggregate: 

```
ERROR: The assigned value for the column tmp_res_table.y has type Long NULL, which cannot be safely coerced to the column's type Int (1 : 13)
insert into tmp_res_table select t0.x as x...
            ^


Exception caught when trying to execute the command:
insert into tmp_res_table select t0.x as x, SUM(t0.y) as y from tc t0 group by x;
```

Log attached: [mlm.log](https://github.com/Hacker0912/RecStep/files/6704995/mlm.log)

Any help is appreciated!

**Comment by Hacker0912** [comment]
Hi Yisu,

The error was caused by the fact that SUM operator was used - whenever you use the SUM operator, the quickstep would assume the possibility of "overflow" and thus for safety reasons, the type of the aggregated result will be cast into Long type. And the fix should be easy: when you define the schema of "res_table" in IDB_DECL, simply define the schema as
res_table(x int, y long). Feel free to reach if you have any questions.

Best,
Zhiwei
________________________________
From: Yisu Remy Wang ***@***.***>
Sent: Wednesday, June 23, 2021 4:37 PM
To: Hacker0912/RecStep ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hacker0912/RecStep] Issue with SUM aggregate (#4)


I ran into some type errors when trying to use the SUM aggregate:

ERROR: The assigned value for the column tmp_res_table.y has type Long NULL, which cannot be safely coerced to the column's type Int (1 : 13)
insert into tmp_res_table select t0.x as x...
            ^


Exception caught when trying to execute the command:
insert into tmp_res_table select t0.x as x, SUM(t0.y) as y from tc t0 group by x;


Log attached: mlm.log<https://github.com/Hacker0912/RecStep/files/6704995/mlm.log>

Any help is appreciated!

**Comment by remysucre** [comment]
That makes sense. However when I tried, there seems to be some parser errors: 

`line 6:13 mismatched input 'long' expecting {TOKEN_INT, TOKEN_FLOAT, TOKEN_DOUBLE, TOKEN_VARCHAR, TOKEN_CHAR, TOKEN_DATE, TOKEN_DATETIME}`

**Comment by Hacker0912** [comment]
I actually recently found the same issue and made change to the code, please pull the repo again and try it on the up-to-date codebase.
________________________________

**Comment by remysucre** [comment]
Using `float` and `double` made some progress, but the types still don't work out: 

`ERROR: The assigned value for the column tmp_res_table.y has type Double NULL, which cannot be safely coerced to the column's type Double (1 : 13)
insert into tmp_res_table select t0.x as x...`

In general, I think it makes more sense to have SUM to have the same type without casting. For example, this program uses the result of SUM recursively and I really think it has to share the same type as the domain of arc: 

arc(x int, y int)
mlm(x int, y int)
mlm(x, x+SUM(y)) :- mlm(z,y), arc(x,z).

**Comment by remysucre** [comment]
Sorry, I only saw your response after typing the above. I'll try, but I think I still need to remove the cast for SUM as above.

**Comment by remysucre** [comment]
Another issue I think I'll have is that SUM in recursion doesn't seem to be supported currently: 
https://github.com/Hacker0912/RecStep/blob/ebd6d5b92b69fa1b185129f48b90f9e703e81d4c/query_generator/sql_query_generator.py#L373

**Comment by Hacker0912** [comment]
That’s intentional since the fix point semantic for recursive sum is ill-defined (i.e., the Datalog program may never terminate.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
